### ISSUE TITLE
Not all trades being bumped

### ISSUE THREAD

**Issue by heysh** [jamieweavis/rocket-league-garage-trade-bumper#7]
**Describe the bug**
Not all of my trades are being bumped. On the second round of bumping, the first half of my trades are within the 15 minute cooldown period and therefore don't get bumped, whilst the second half are not within the cooldown period, so they do get bumped.

**How to reproduce**
1. Set the bumper to bump all trades
2. Leave the timer at 15 minutes
3. Press start
4. Wait 15 minutes and observe status of trades

**Expected behavior**
I am expecting all trades to get bumped.

**Comment by jamieweavis** [comment]
Hi @heysh, thanks for the bug report! 🙌 

This will be because I added a delay between bumps to stagger them in #5 - I forgot to account for the extra time added between between bumps meaning that some of the last trades to be bumped in the previous round will be under the 15 minute cooldown when then fails to bump

I'll look at fixing this tonight!
