### ISSUE TITLE
None of my trades are bumped and bug with 0 minutes refresh

### ISSUE THREAD

**Issue by doreori** [jamieweavis/rocket-league-garage-trade-bumper#8]
**Describe the bug**
Hello, first of all, thanks for your work it worked fine until the update from yesterday :/ I have the refresh from the website but it doesnt seem to bump the trades, I only have 1 tab opened. 

**How to reproduce**
1. Go to the profile page
2. Click on start the timer
3. Wait
4. See a refresh from the page but none of my trades bumped

**Other problem**
When I set the timer to 0 minutes, after 1 minute of loading from the website I get an error from rocket league saying that I exceded the amout of attemps to connect to the website 
![image](https://user-images.githubusercontent.com/38520109/109043968-23c11c00-76d2-11eb-93fe-93f2ba8b92da.png)

**Expected behavior**
Trades bumped

**Additional context**
Tested with or without adblock

**Comment by doreori** [comment]
I've used the chrome version which was updated yesterday Ill use the zip version to test it out

**Comment by jamieweavis** [comment]
Hi @doreori,

Thanks for the report, I'm not sure why it's not working for you because the latest version (`v0.4.2`) works fine for me

> 1. Go to the profile page

Are you sure that you are on the correct page? Instead of being on your profile page you should be on your trades page, like this: https://rocket-league.com/trades/YOUR_USERNAME_HERE

Regarding settings it to 0 minutes, you shouldn't be able to do that and I will make it so that you can't 😄

**Comment by doreori** [comment]
Yep I'm just dumb sorry, works fine !
